name = "FlyClassifiers"
uuid = "87f929f6-1c70-4c8c-9b04-ad225bbb75ed"
version = "0.1.0"
authors = ["Davide Toniatti <davide.toniatti@students.uniroma2.eu>"]

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ChunkSplitters = "3.1.2"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
SparseArrays = "1.12.0"
StatsBase = "0.34.9"
